# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# User.create(name: 'hanako_kirameki1', email: 'hanako_kirameki1@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki2', email: 'hanako_kirameki2@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki3', email: 'hanako_kirameki3@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki4', email: 'hanako_kirameki4@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki5', email: 'hanako_kirameki5@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki6', email: 'hanako_kirameki6@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki7', email: 'hanako_kirameki7@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki8', email: 'hanako_kirameki8@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki9', email: 'hanako_kirameki9@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki10', email: 'hanako_kirameki10@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki11', email: 'hanako_kirameki11@example.com', password: 'password', profile: 'aa')
# User.create(name: 'hanako_kirameki12', email: 'hanako_kirameki12@example.com', password: 'password', profile: 'aa')
# Relationship.find_or_create_by(follower_id: 8, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 3)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 4)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 5)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 6)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 7)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 1)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 9)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 10)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 11)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 12)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 13)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 14)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 15)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 16)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 17)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 18)
# Relationship.find_or_create_by(follower_id: 8, followed_id: 19)
# Relationship.find_or_create_by(follower_id: 3, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 4, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 5, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 6, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 7, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 9, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 10, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 11, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 12, followed_id: 2)
# Relationship.find_or_create_by(follower_id: 13, followed_id: 2)

Relationship.find_or_create_by(follower_id: 2, followed_id: 8)
Relationship.find_or_create_by(follower_id: 3, followed_id: 8)
Relationship.find_or_create_by(follower_id: 4, followed_id: 8)
Relationship.find_or_create_by(follower_id: 5, followed_id: 8)
Relationship.find_or_create_by(follower_id: 6, followed_id: 8)
Relationship.find_or_create_by(follower_id: 7, followed_id: 8)
Relationship.find_or_create_by(follower_id: 1, followed_id: 8)
Relationship.find_or_create_by(follower_id: 9, followed_id: 8)